<a href="https://colab.research.google.com/github/Andrea-datasc/github-slideshow/blob/master/T_SDS_HP_DataPreprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import the libraries
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt



In [ ]:
# import the dataset. set X= a matrix of features (independent variables) and y = vector of variables (dependent variables: purchased)

from google.colab import files
data_to_load = files.upload()


Saving Data.csv to Data.csv


In [ ]:
data = pd.read_csv('Data.csv')

In [ ]:
X = data.iloc[:,:-1].values   # locate indexes iloc all rows :, specify columns with indexes all columns except the last one
y = data.iloc[:, -1].values

In [ ]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [ ]:
# Dealing with missing data
# replace with avg of salaries
# best library scilitlearn most of half models built with it
from sklearn.impute import SimpleImputer 
imputer = SimpleImputer(missing_values = np.nan, strategy='mean')
# fit method will look for missing values in columns (all numerical) age and salary for all rows, compute avg and then use transform method
imputer.fit(X[:,1:3])
X[:,1:3] = imputer.transform(X[:,1:3])

In [ ]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
# Encoding Categorical Data
#turn the strings country names into categories 1 hot encoding, turn 3 country=ies into 3 columns, create a vector for each country
# so there is no numerical order in the countries
# then also replace purchase into 0 and 1

In [ ]:
# Encoding the independent variable
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers =[('encoder',OneHotEncoder(),[0])], remainder ='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
# 3 new columns
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
# Encoding the dependent variable no into 0, yes into 1 with Label Encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [ ]:
# Splitting the dataset into the Training set and test set
# Feature Scaling AFTER Splitting into training and test sets. Test set is sth you are not supposed to have, that's why feature scaling
# is applied after splitting to avoid information leakage

# Splitting the dataset into traning set and test set with a function of sklearn
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test  = train_test_split(X, y, test_size = 0.2, random_state =1)



In [ ]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [ ]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [ ]:
print(y_test)

[0 1]


In [ ]:
# Feature scaling to avoid some features dominated from other features. No all datasets need this.
# i.e .multiple linear regression
# use standard scaling 
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
# do not apply feature scaling to country vectors = dummy variables so that we do not lose interpretations
# only apply feature scaling to numerical values
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])  # look at the matrix with vectors
X_test[:, 3:] = sc.transform(X_test[:, 3:])



In [ ]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [ ]:
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
